name: 'Demo Vicente'

on:
  push:
    branches: main
    
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Build'
        run: |
          echo 'Build application...'

  deploy:
     runs-on: ubuntu-24.04
     needs: build
     steps:
       - name:  "Deploy"
         run: echo "Deploy app"
